import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { MenuProvider } from "@/context/MenuContext";

import { SensorProvider } from "@/context/SensorContext";
import QueryProvider from "@/components/providers/QueryProvider";
import { Toaster } from "sonner";
import AuthProvider from "@/components/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <AuthProvider>
          <SensorProvider>
            <MenuProvider>
              <QueryProvider>
                <div className="flex flex-1 flex-col min-h-screen">
                  <main className="flex-1 p-4 h-full">
                    {children}
                    <Toaster
                      position="top-center"
                      toastOptions={{
                        style: {
                          color: "white",
                          fontWeight: "bold",
                          borderRadius: "8px",
                        },
                      }}
                    />
                  </main>
                </div>
              </QueryProvider>
            </MenuProvider>
          </SensorProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
