import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/components/layout/Header";
import { AppSidebar } from "@/components/layout/Sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { MenuProvider } from "@/context/MenuContext";
import { MQTTProvider } from "@/context/MqttContext";
import { SensorProvider } from "@/context/SensorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = "674fa232ac2f55026050b4e7";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <SensorProvider userId={userId}>
          <MQTTProvider>
            <MenuProvider>
              <div className="flex flex-1 flex-col h-full">
                <main className="flex-1 p-4 h-full">{children}</main>
              </div>
            </MenuProvider>
          </MQTTProvider>
        </SensorProvider>
      </body>
    </html>
  );
}
